# Generated by Django 3.2.12 on 2022-02-19 13:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Depart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='部门名称')),
                ('created_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='成立时间')),
            ],
        ),
    ]
